### ISSUE TITLE
missing autotools_stage.bbclass 

### ISSUE THREAD

**Issue by joeusercz** [Taapat/vuplus-openpli-oe-core#5]
ERROR: ParseError at /home/builder/vuplus-fulan-openpli-oe-core/meta-openembedded/meta-oe/recipes-extended/scsirastools/scsirastools_1.6.4.bb:17: Could not inherit file classes/autotools_stage.bbclass

**Comment by Taapat** [comment]
Remove autotools_stage in scsirastools_1.6.4.bb
autotools_stage now is removed in openembedded because it is included in autotools and no longer needed.
This should by fixed in meta-openembedded, I hope they do it soon, and therefore I do not want to create bbappend file for this.

**Comment by Taapat** [comment]
I see that they have already fix it: https://github.com/openembedded/meta-openembedded/commit/5e99b0dc8789185132b9127fb26dcb8b218306d5
I update meta-openembedded to fix this issue.

**Comment by LoveMeow** [comment]
Hi, I am on the pyro branch, I still get this error
ERROR: ParseError at /home/rama/repositories/poky/meta-openembedded/meta-oe/recipes-extended/scsirastools/scsirastools_1.6.4.bb:17: Could not inherit file classes/autotools_stage.bbclass
I just cloned the repo today

**Comment by Taapat** [comment]
Are you write in the correct place?
There is no pryo branch here.
